on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - sisyphus
          - p10
        arch:
          - amd64
          - arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.arch }}

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: "alt:${{ matrix.branch }}"
          options: |
            --platform linux/${{ matrix.arch }}
            --volume ${{ github.workspace }}/:/workspace
            --env GH_TOKEN=${{ github.token }}
            --env ALLOW_ROOT_USER=1
          run: |
            cd /workspace
            apt-get update && apt-get -y install git etersoft-build-utils
            curl -sL https://eepm.ru/epm.sh | bash /dev/stdin ei
            rpmgp -l *.spec | epm --skip-installed --auto install 
            rpmgs -f *.spec
